<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WercLib\Module'                                   => __DIR__ . '/Module.php',
    'WercLib\Db\LanguageInterface'                     => __DIR__ . '/src/WercLib/Db/LanguageInterface.php',
    'WercLib\Entity\AbstractEntity'                    => __DIR__ . '/src/WercLib/Entity/AbstractEntity.php',
    'WercLib\Service\Initializer\Db'                   => __DIR__ . '/src/WercLib/Service/Initializer/Db.php',
    'WercLib\Service\Initializer\DbLanguage'           => __DIR__ . '/src/WercLib/Service/Initializer/DbLanguage.php',
    'WercLib\Stdlib\UrlHostParser'                     => __DIR__ . '/src/WercLib/Stdlib/UrlHostParser.php',
    'WercLib\Stdlib\UrlParser'                         => __DIR__ . '/src/WercLib/Stdlib/UrlParser.php',
    'WercLib\Stdlib\UrlParserInterface'                => __DIR__ . '/src/WercLib/Stdlib/UrlParserInterface.php',
    'WercLib\View\Helper\AbstractCalendar'             => __DIR__ . '/src/WercLib/View/Helper/AbstractCalendar.php',
    'WercLib\View\Helper\Attachments'                  => __DIR__ . '/src/WercLib/View/Helper/Attachments.php',
    'WercLib\View\Helper\Calendar'                     => __DIR__ . '/src/WercLib/View/Helper/Calendar.php',
    'WercLib\View\Helper\Coder'                        => __DIR__ . '/src/WercLib/View/Helper/Coder.php',
    'WercLib\View\Helper\Factory\FlashMessagesFactory' => __DIR__ . '/src/WercLib/View/Helper/Factory/FlashMessagesFactory.php',
    'WercLib\View\Helper\FlashMessages'                => __DIR__ . '/src/WercLib/View/Helper/FlashMessages.php',
    'WercLib\View\Helper\Fotogalerie'                  => __DIR__ . '/src/WercLib/View/Helper/Fotogalerie.php',
    'WercLib\View\Helper\RenderBootstrapForm'          => __DIR__ . '/src/WercLib/View/Helper/RenderBootstrapForm.php',
    'WercLib\View\Helper\Rewrite'                      => __DIR__ . '/src/WercLib/View/Helper/Rewrite.php',
    'WercLib\View\Helper\RouteLanguage'                => __DIR__ . '/src/WercLib/View/Helper/RouteLanguage.php',
    'WercLib\View\Helper\ShareLink'                    => __DIR__ . '/src/WercLib/View/Helper/ShareLink.php',
    'WercLib\View\Helper\ZkratText'                    => __DIR__ . '/src/WercLib/View/Helper/ZkratText.php',
);
